### ISSUE TITLE
[Request] Correspond to the new Alert syntax

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/crmsh#280]
Hi Kristoffer,

Alert's syntax is changed if the following modifications are included.
 - https://github.com/ClusterLabs/pacemaker/pull/1332

Corresponding version is also required for crmsh.

Best Regards,
Hideo Yamauchi.

**Comment by krig** [comment]
Thank you!

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

This is an enhancement rather than a bug.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

Is the crm shell still taking a long time to deal with this new syntax?

The Japanese community is using the crm shell, so I am longing for this response.

Best Regards,
Hideo Yamauchi.

**Comment by krig** [comment]
Hi Hideo-san,

I will make sure we get this fixed in the next release, thank you for reminding me of the change! I missed the merge of the syntax change.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

Okay!

Please do release it with the function of Bundle.
 - https://github.com/ClusterLabs/crmsh/issues/191

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,


In the Japanese community, the crm shell still adopts 2.1.9.
We need 2.1.10 release as a function supporting alert and bundle functions.

We will move to the crm shell 2.x series will be after Pacemaker 2.x is released.

Best Regards,
Hideo Yamauchi

**Comment by krig** [comment]
Hi Hideo-san,

Thank you for your input.

We have made quite large changes to crmsh in the master branch due to the necessity of porting crmsh to Python 3, and so we are bumping the major version number again: The next release will be crmsh 4. I will look at backporting the support for alerts and bundles to the 2.1 series once we have merged support in master.

Thank you for your input!

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

Okay!
The Japanese community is looking forward to the release of crm shell 2.1.10.

Many thanks!
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

Thanks for the correction
We are planning to use 2.1.10.

Can you create a 2.1.10-rc corresponding to this fix?

Best Regards,
Hideo Yamauchi.

**Comment by krig** [comment]
Hi Hideo-san,

Backporting these new features to the crmsh 2.1 branch is non-trivial, it will take some time. Due to the port to Python 3, there have been a lot of changes to the code.

I hope to have time to do this port soon, but I cannot promise a delivery date.

We will soon release crmsh 4.1 which will be based on Python 3, and have full support for the new alerts syntax, container bundle syntax etc.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

Thanks for your comment.

Okay!
We will discuss about the difficulty in dealing with 2.1.10.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

Although crmsh 4.1 is compatible with python 3, will it work with python 2. x?

Many thanks,
Hideo Yamauchi.

**Comment by krig** [comment]
Hi Hideo-san,

crmsh 4.1 is only compatible with Python 3. Perhaps we can provide these features also to the python 2 branch. However, is Python 3 not available for RHEL 7.3?

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

> crmsh 4.1 is only compatible with Python 3. Perhaps we can provide these features also to the python 2 branch.

Okay!

> However, is Python 3 not available for RHEL 7.3?

I will check, but I do not want to recommend it much in the Japanese community because I think that it is necessary to additionally install the python 3 package separately in RHEL 7.3.

Best Regards,
Hideo Yamauchi.

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

Please teach me.

What version of crmsh is adopted in the latest distribution where SUSE is released?

Best Regards,
Hideo Yamauchi.

**Comment by krig** [comment]
Hello Hideo-san,

SLE 12 is currently using the `crmsh-3.0` 3 series stable branch, and this is the latest released distribution by SUSE.

In this release, we do not yet have container bundles or the extended alert syntax in pacemaker, which is why this release of crmsh lacks support for those features.

Right now, we are working on SLE 15, which will include these features. SLE 15 will not have python 2, this is why we have ported crmsh to python 3. This release will include support for the new features in pacemaker.

The need to port crmsh to python 3 has taken quite some effort. At the moment, we are busy working on this release. This is why we haven't found time to focus on backporting to older releases yet, apologies for that.

Cheers,
Kristoffer

**Comment by HideoYamauchi** [comment]
Hi Kristoffer,

Thank you for your detailed comment.

We will consider a little more.

Best Regards,
Hideo Yamauchi.
