### ISSUE TITLE
Several launch errors

### ISSUE THREAD

**Issue by ijklsd** [ClusterLabs/crmsh#424]
This is with crmsh 3.0.0 under CentOS 7 upgraded and patched to the latest:

# crm cluster init --name OneCluster --nodes "one two three"
! No watchdog device found. If SBD is used, the cluster will be unable to start without a watchdog.
Do you want to continue anyway (y/n)? y
! Firewall: Could not open ports tcp=30865|5560|7630|21064, udp=
/root/.ssh/id_rsa already exists - overwrite (y/n)? y
  Generating SSH key
  Configuring csync2
  Generating csync2 shared key (this may take a while)...ERROR: cluster.init: Can't create csync2 key /etc/csync2/key_hagroup

Here is what I know:

1) There are no iptables rules in the system.
2) firewalld is not running in the system.
3) pacemaker 1.1.19 and corosync 2.4.3.4 are both installed.
4) Hosts one, two and three are resolvable by DNS, and can be accessed from each other via SSH.

Here is what I don't know:

1) What watchdog is it talking about? Is it necessary?
2) Why is it unable to open those ports, when no firewalld is running and there are no iptables rules?
3) /etc/csync2 is missing. Where is that supposed to be coming from?

**Comment by krig** [comment]
1. SBD (fencing mechanism) requires a watchdog device. For most purposes, the `softdog` kernel module is sufficient, so loading that should be OK.

2. It's perhaps a bit misleading, all it's saying is that it couldn't identify any running firewall and showing which ports it intends to use, so that in case you DO have a firewall or iptables configured you can sort that out manually.

3. csync2 is a separate project that the bootstrap procedure depends on. Source here: https://github.com/LINBIT/csync2. Unfortunately I don't know if it is packaged for CentOS. We are working on removing this dependency, but at the moment it is still there.
