### ISSUE TITLE
nvpairs without value are not allowed

### ISSUE THREAD

**Issue by krig** [ClusterLabs/crmsh#71]
The crmsh syntax no longer allows only foo instead of foo="" as nvpair value assignments.

I don't want to allow just foo as this limits the possible extensions of the language too much, but enabling the use of a trailing = to signify empty values should be allowed. That is, foo= rather than foo.

**Comment by lge** [comment]
Note: it is apparently valid XML to have no value attribute at all.
The xml.orig -> crmsh -> xml.re-converted sanity check bombs out,
because re-converted then contains a  >> value="" << attribute that is not pressend in orig.

See below:

DEBUG: found pacemaker version: 1.1.12
DEBUG: nvpair!=nvpair: attributes differ: {'id': 'stonith_ipmi-karl-instance_attributes-verbose', 'name': 'verbose'} != {'name': 'verbose', 'value': '', 'id': 'stonith_ipmi-karl-instance_attributes-verbose'}


DEBUG: validation failed: <primitive class="stonith" id="stonith_ipmi-karl" type="fence_ipmilan"><instance_attributes id="stonith_ipmi-karl-instance_attributes"><nvpair id="stonith_ipmi-karl-instance_attributes-pcmk_host_list" name="pcmk_host_list" value="karl"/><nvpair id="stonith_ipmi-karl-instance_attributes-verbose" name="verbose"/><nvpair id="stonith_ipmi-karl-instance_attributes-action" name="action" value="reboot"/><nvpair id="stonith_ipmi-karl-instance_attributes-ipaddr" name="ipaddr" value="10.43.242.221"/><nvpair id="stonith_ipmi-karl-instance_attributes-login" name="login" value="root"/><nvpair id="stonith_ipmi-karl-instance_attributes-passwd" name="passwd" value="dummy"/><nvpair id="stonith_ipmi-karl-instance_attributes-method" name="method" value="onoff"/></instance_attributes><operations><op id="stonith_ipmi-karl-start-0" interval="0" name="start" timeout="60"/><op id="stonith_ipmi-karl-stop-0" interval="0" name="stop" timeout="60"/><op id="stonith_ipmi-karl-monitor-600" interval="600" name="monitor" timeout="60"/></operations><meta_attributes id="stonith_ipmi-karl-meta_attributes"><nvpair id="stonith_ipmi-karl-meta_attributes-target-role" name="target-role" value="Started"/></meta_attributes></primitive>

-> primitive stonith_ipmi-karl stonith:fence_ipmilan params pcmk_host_list=karl verbose action=reboot ipaddr=10.43.242.221 login=root passwd=dummy method=onoff op start interval=0 timeout=60 op stop interval=0 timeout=60 op monitor interval=600 timeout=60 meta target-role=Started

-> <primitive id="stonith_ipmi-karl" class="stonith" type="fence_ipmilan"><instance_attributes id="stonith_ipmi-karl-instance_attributes"><nvpair name="pcmk_host_list" value="karl" id="stonith_ipmi-karl-instance_attributes-pcmk_host_list"/><nvpair name="verbose" value="" 

^^ THERE.

id="stonith_ipmi-karl-instance_attributes-verbose"/><nvpair name="action" value="reboot" id="stonith_ipmi-karl-instance_attributes-action"/><nvpair name="ipaddr" value="10.43.242.221" id="stonith_ipmi-karl-instance_attributes-ipaddr"/><nvpair name="login" value="root" id="stonith_ipmi-karl-instance_attributes-login"/><nvpair name="passwd" value="dummy" id="stonith_ipmi-karl-instance_attributes-passwd"/><nvpair name="method" value="onoff" id="stonith_ipmi-karl-instance_attributes-method"/></instance_attributes><operations><op name="start" interval="0" timeout="60" id="stonith_ipmi-karl-start-0"/><op name="stop" interval="0" timeout="60" id="stonith_ipmi-karl-stop-0"/><op name="monitor" interval="600" timeout="60" id="stonith_ipmi-karl-monitor-600"/></operations><meta_attributes id="stonith_ipmi-karl-meta_attributes"><nvpair name="target-role" value="Started" id="stonith_ipmi-karl-meta_attributes-target-role"/></meta_attributes></primitive>

DEBUG: object stonith_ipmi-karl cannot be represented in the CLI notation

The thing is: the agent apparently wants to be called with "--verbose".
NOT --verbose="".

Any chance supporting that, too?

**Comment by krig** [comment]
Hmm, yes, if that is valid, I guess we should support it. But I am not happy about it! ;) The syntax will be even more ambiguous, but I guess it can't be avoided.

**Comment by krig** [comment]
@lge Could you test this version (#2a45993) with your CIB so I can be sure that this fixes it?

**Comment by krig** [comment]
This should be fixed now I hope. :)
